-- Carga de matriz de seguimiento de trámites varios, generada desde CSV el 2026-07-08.
-- Oculta procesos anteriores para que el dashboard refleje esta nueva matriz como base activa.
update public.processes set activo=false where codigo_proceso not like 'TRV-2026-%';
insert into public.areas(nombre,activo) values ('AVALUOS Y CATASTROS',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('CLIENTE EXTERNO',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('DIRECCIÓN DE OBRAS PUBLICAS',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('DISEÑO DE LA OBRA PÚBLICA',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('HABILITACIÓN DE SUELO Y EDIFICACIÓN',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('HGADPCH',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('JUSTICIA Y CONTROL TERRITORIAL',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('OOPP',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('PARTICIPACIÓN CIUDADANA',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('PLANIFICACIÓN, HABITAT Y DESARROLLO',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('PROCURADURÍA',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('RIOBAMBA - EP',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('RUTAS EP',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('SECRETARÍA GENERAL',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('Sin entidad actual',true) on conflict (nombre) do update set activo=true;
insert into public.areas(nombre,activo) values ('TALENTO HUMANO',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('DIRPLAN',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('DISEÑO',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Desmembración',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Documentos',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Expropiaciones',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Mapas',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Normativa',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('OTROS',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Subdivisión',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Transferencia de Predios Municipales',true) on conflict (nombre) do update set activo=true;
insert into public.process_types(nombre,activo) values ('Trámite Vario',true) on conflict (nombre) do update set activo=true;
insert into public.process_statuses(nombre,color,orden,activo) values ('Planificado','#64748b',1,true) on conflict (nombre) do update set color=excluded.color, orden=excluded.orden, activo=true;
insert into public.process_statuses(nombre,color,orden,activo) values ('En Ejecución','#0f766e',2,true) on conflict (nombre) do update set color=excluded.color, orden=excluded.orden, activo=true;
insert into public.process_statuses(nombre,color,orden,activo) values ('En Revisión','#7c3aed',3,true) on conflict (nombre) do update set color=excluded.color, orden=excluded.orden, activo=true;
insert into public.process_statuses(nombre,color,orden,activo) values ('Finalizado','#2563eb',4,true) on conflict (nombre) do update set color=excluded.color, orden=excluded.orden, activo=true;
insert into public.priorities(nombre,color,orden,activo) values ('Alta','#dc2626',1,true) on conflict (nombre) do update set color=excluded.color, orden=excluded.orden, activo=true;
insert into public.priorities(nombre,color,orden,activo) values ('Media','#d97706',2,true) on conflict (nombre) do update set color=excluded.color, orden=excluded.orden, activo=true;
insert into public.priorities(nombre,color,orden,activo) values ('Baja','#16a34a',3,true) on conflict (nombre) do update set color=excluded.color, orden=excluded.orden, activo=true;
06ABR2026 Arq. Verdesoto envia a cliente externo solicitando la documentación para el alcance
15ABR2026 Se sube el alcance del trámite para avanzar con el proyecto, sigue pendiente los documentos firmados por el Sr. Haro
16ABR2026 Se asigna a Arq. Verdesoto para revisión
23ABR2026 Se asigna a Arq. Llangari para emisión de IPRUS #1152332
27ABR2026 Se remite a Catastros con memorando #1155940
04MAY2026 Se designa a Arq. Verdesoto con sumilla 4 #1159139
05MAY2026 Arq. Verdesoto pide revisión IPRUS, se remite a Catastros #1160752
08MAY2026 Catastros remite IPRUS corregido #1162924 se reasigna a Arq. Verdesoto
18MAY2026 Abg. Subia emite memo: Traslado trámite de desmembración para emisión de informe técnico, se reasigna a Arq. Verdesoto 1169045
04JUN2026 Arq. Verdesoto envía informe con #1181024
09JUN2026 Abg. Subia emite informe juridico favorable #1183403 se reasigna a la Arq. Verdesoto
09JUN2026 Resolusión Administrativa firmada y reasignada a la Abg. Subia
15JUN2026 A la espera de despacho, pues los planos no se encuentran firmados por el usuario.',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
31MAR2026 Abg. Mariño remite informe Juridico al Ing. Remache #1134815
28ABR2026 Reasignado a Abg. Mariño con Sumilla 3
12MAY2026 Se firma Resolución de Administrativa y se envia a Cliente Externo #1165203
14MAY2026 Se le solicitó a Gabi Escobar se comunique con Mesías Cuji para continuar con el proceso',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 27MAR2026 Emisión del IPRUS en Catastro 
30MAR2026 Reasignado a Arq. Verdesoto para revisión
14ABR2026 Se asigna Abg. Subia como Secretaria Ad-Hoc
15ABR2026 En bandeja del Arq. Tello director Subrogante, para suscribir
24ABR2026 Se actualizan los datos, en bandeja de Ing. Remache para suscribir
27ABR2026 Se reasigna a Arq. Bonifaz para continuar con el proceso
28ABR2026 Se reasigna a Arq. Verdesoto para informe técnico #1156437
13MAY2026 Arq. Verdesoto emite Informe con Observaciones se reasigna a la Arq. Bonifaz #1166123
20MAY2026 Arq. Bonifaz envía solicitud de rectificación de IPRUS a Catastros #1171927
27MAY2026 Catastros responde con memo #1174706 Asignado a Arq. Bonifaz
30MAY2026 Se remite a Cliente Externo para subsanar observaciones
16JUN2026 Se asigna a la Arq. Bonifaz para revisión',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 19MAR2026 Entrega de Informe y Planos de Propuesta de Subdivisión Arq. Carrasco 
20MAR2026 En conocimiento del Alcalde y el Consejo Cantonal para su aprobación mediante ordenanza, Alcaldía Reasigna a Catastros, Participación Ciudadana y Registro de la Propiedad 
25MAR2026 Registro de la Propiedad reasigna el tramite a Planificación
25MAR2026 Reasignado a Irene Lopez 
30MAR2026 Se remite a Procuraduría
13ABR2026 Responde Procuraduría Solicitando Expediente Completo y Original, en bandeja de Arq. Tello
16ABR2026 Se envia Recopilación de documentos EGOB en Fisico a Procuraduria #1150060
23ABR2026 Procuraduría envía Criterio para subdivisón a Alcaldía #1154178
24ABR2026 Se reasigna a Secretaría General
29ABR2026 Se remite a Taty Puyol a fin de que sea incorporado en sesión de Consejo #1154178
06MAY2026 Se aprueba la subdivisión en sesión de Concejo #1163887, se remite a Alcaldía y Procuraduría, en bandeja de Irene Lopez y Archivado por Marcelo Treviño
13MAY2026 Alcaldía remite a Habitat, Catastros y Registro de la Propiedad #1163887
09JUN2026 Registro de la propiedad remite a Procuraduría debido a que existe una prohibición de enajenar',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
26MAR2026 Arq. Horna entrega a la Arq. Alvear planos y memoria tecnica
Remitir el Proyecto a Procuraduria
08JUN2026 Insisto de respuesta al memo 1062409 con #1179799',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 20MAR2026 Se envia a Rentas para la Emisión al Fondo de Cesantías
25MAR2026 En espera de pago Emisión Realizada #1125940
28MAY2026 Se envía a Procuraduría el Expediente Integro #1175876',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: Realizar el Borrador una vez se termine la actualización del PUGS',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 24ABR2026 Se envia Resolución a Alcaldía con Memo GADMR-DG-PHDU-2026-2121-M
26ABR2026 Se remite a Procuraduría
04MAY2026 Se remite a Castastros #1159344
08MAY2026 Se remite a Procuraduría #1163813, emite borrador de IPRUS y recomienda correcciones al Manual de Procedimiento Administrativo
13MAY2026 Procuraduría envía Memo GADMR-PROC-2026-1341-M se reasigna a Arq. Bonifaz
18MAY2026 Se remite a Catastros #1165861
20MAY2026 Catastros responde con memo #1171678 
21MAY2026 Arq. Bonifaz envia memo a D. Talento Humano #1172519
01JUN2026 TH responde con observaciones #1178203 
02JUN2026 Se reasgina a los Ing. Maldonado y Ortiz #1178203
08JUN2026 Ing. Ortiz remite informe con observaciones subsanadas, se reasigna a la Arq. Bonifaz para revisión y remitir al Alcalde #1183243
19JUN2026 Atendido mediante Resolución Nro. GADMR-ALC-2026-0037-R',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 12MAY2026 Se envió a Alcaldía y ellos remiten a Procuraduría 
15MAY2026 Procuraduría Archiva el trámite Por Conocido
29MAY2026 Nos remite Informe con Observaciones #1176987 
30MAY2026 Se asigna a la Arq. Bonifaz para subsanar las observaciones',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
30MAR2026 Arq. Sebastián Yanez esta elaborando un Cronograma para sacar el proyecto a Finales de MAYO
07ABR2026 Reasignado a Arq. Yanez y Ing. Pazmiño para proceder con los documentos habilitantes
09JUN2026 Reasigna al Arq. Perez debido a la renuncia del Arq. Yanez',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 24MAR2026 Reunión con Representantes de la Coop. 
19JUN2026 Reunión para presentar el alcance al proyecto',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
08MAY2026 Catastros solicita actualización del Certificado de Gravamen, se remite al Registro de la Propiedad
12MAY2026 Registro de la Propiedad remite Solicitud a Arq. Andrés Vasquez #1163311
04MAY2026 Arq. Andrés Vasquez nos envía respuesta no favorable de la incorporación a los bienes municipales #1180028',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
25MAR2026 Reasignado a Adriana Costales con Sumilla 4 
07ABR2026 Se envía a Alcaldía el Informe técnico para comodato a favor de CONAGOPARE #1142710 
17ABR2026 Se emite el informe Financiero y se reasigna a Catastros #1151421
05MAY2026 Catastros nos reasigna para continuar con el proceso
08MAY2026 Ing. Remache remite a Procuraduría para continuar con el proceso
02JUN2026 Subprocurador remite solicitud de documentos, en bandeja del Ing. Remache #1179367
04JUN2026 Ing. Remache reasigna a Procuraduría ya que los documentos se enviaron anteriormente #1179367
09JUN2026 Procuraduría Solicita Certificado de Gravamen #1183689 
10JUN2026 Resgitro de la Propiedad remite solicitud a Procuraduría #1185516
19JUN2026 Se reasigna al Ing. Juan Diego con #1190325
30JUN2026 Para sesión ordinaria de concejo.',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 19MAR2026 Se envía mediante memorando a la Alcaldía
26MAR2026 Se remite a Procuraduría 
31MAR2026 Produraduría Recibe el Expediente Fisico 
07ABR2026 Procuraduría remite informe a Catastros
24ABR2026 Se asigna a Carlos Tene para elaboración de Planimetría #1143230
24ABR2026 Se reasigna a Jefe de Catastros para su revisión
28ABR2026 En bandeja del Director Arq. Tello #1155276 
29ABR2026 En bandeja del Alcalde #1157979
04MAY2026 Se remite a Procuraduría con Sumilla 4
14MAY2026 Se remite a Catastros con #1167361
04JUN2026 Se remite a Procuraduría con #1180119',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: Conseguir un contacto de la Liga Deportiva Despacho, PENDIENTE IRENE LOPEZ',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
27MAR2026 Se envía a Lorena Granizo (Analista de Atención Ciudadana) mediante memorando #1136338
02JUN2026 Enviamos insisto de respuesta #1179827
18JUN2026 Se reasigna la respuesta a la Ing. García #1190948
23JUN2026 Se remite Matriz de Información a Justicia y Control Territorial',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Existe un eje vial emitido en el 2022 (EGob #536398)
Informe enviado a Ing. Silvana Vasquez, Gerente General de RIOBAMBA-EP
Enviado mediante Memorando 1132117 a Riobamba-EP',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
03MAY2026 Se envía a Talento Humano con #1157860 para su coordinación',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 24ABR2026 Se dio respuesta con memo 1134054',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
01JUN2026 Se solicita a Paticipación Ciudadana la socialización con memo #1178574 
02JUN2026 Se solicita los documentos habilitantes a las diferentes direcciones # 1179429
05JUN2026 Adjuntan Ficha Registral Actualizada 80475 (Registro de la Propiedad)
17JUN2026 Adjuntan Certificación de PDYOT (Dirección General de Gestión Estratégica)
24/06/2026 Ficha Catastral #1194881
Informe técnico de Riesgos (Dirección General de Gestión Estratégica-Jefatura de Gestión Integral de Riesgos)
Certificación Ambiental (Dirección General de Gestión Ambiental)',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
No hay Avances',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: Ing. Pazmiño solicita levantamiento planimetrico al Arq. Tene
Se cuenta con la ortofoto, y se avanzará con el proyecto con baja prioridad',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
29ABR2026 Ing. Pumagualli solicita se realicen modificaciones
En espera de Ing. Electrico #1179441',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 18MAY2026 Se solicita información Topográfica y Catastro con #1169873 
05JUN2026 Se reasigna Fase 1 al Ing. Borja para continuar el proceso de Lourdes Macaxi',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
01ABR2026 Ing. Pazmiño solicita los Documentos Habilitantes con Memo #1140088 Nro. GADMR-J-DOP-2026-0017-M
06ABR2026 Memo #1141520 enviado a las direcciones correspondientes, para documentos habilitantes
07ABR2026 Ficha Registral emite Registro de la Propiedad
13ABR2026 Gestión Ambiental emite Certificación Ambiental
17ABR2026 Gestión Estrategica emite Certificación de PDYOT
27ABR2026 Se dio la Socialización en el Mercado Mayorista a las 16:30 para el Informe de Socialización 
29ABR2026 Secretaría de Concejo emite Comodato #1158136
29ABR2026 Gestión Estrategica emite Informe de Socialización #1158510
21MAY2026 Se entrega el Proyecto a OOPP #1172489',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
14ABR2026 se envia a la ERSA por que hay que actualizar la aprobación, esperando revisión
11MAY2026 existen observaciones por subsanar, en espera de Ing. Electrico en el equipo
02JUN2026 Se envian las correcciones a la EERSA en espera de Aprobación
02JUN2026 Nos responde Riobamba EP los parámetros de diseño #1179236 se reasigna a la Ing. Erika Calderón
05JUN2026 Ing. Calderón Archiva al anexar el documento al expediente #1179236',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: En espera de entrega de los requisitos acordados CONSULTAR CON EL DIRECTOR DE PLANIFICACION DEL GADPCH
Dejar pendiente, no se sabe si se alcance con esto',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
Observación: 11MAR2026 enviado en físico Oficio 0005-GPHDU-2026',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
15ABR2026 OOPP emite memo con respuesta a la solicitud, indica que información se encuentra en el archivo disponible para revisión #1148933
23ABR2026 Se reasigna a la Ing. Pazmiño para su conocimiento
Se va a encargar la dirección de RUTAS EP',null,false,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
08ABR2026 Se llama a mesa tecnica para el lunes 13MAR2026 para revisar con cultura, obras y compras publicas
14ABR2026 Se envía el .zip de la Consultoría a D. Cultura #1165937
15MAY2026 Talento Humano envía aprobación para consultoría en Bandeja de la Ing. Pazmiño #1168062
22MAY2026 Asignado a los Técnicos Erika Calderón, Gabriel Perez, Daniel Orozco',null,true,'Interna',true,'2026-07-08T00:00:00Z','2026-07-08T00:00:00Z') on conflict (codigo_proceso) do update set area_id=excluded.area_id, tipo_proceso_id=excluded.tipo_proceso_id, nombre_proceso=excluded.nombre_proceso, responsable_principal=excluded.responsable_principal, responsable_secundario=excluded.responsable_secundario, fecha_inicio=excluded.fecha_inicio, fecha_fin_programada=excluded.fecha_fin_programada, fecha_fin_real=excluded.fecha_fin_real, estado_id=excluded.estado_id, prioridad_id=excluded.prioridad_id, porcentaje_avance=excluded.porcentaje_avance, dependencia_externa=excluded.dependencia_externa, documento_respaldo=excluded.documento_respaldo, proxima_accion=excluded.proxima_accion, objetivo=excluded.objetivo, observaciones=excluded.observaciones, fecha_proxima_revision=excluded.fecha_proxima_revision, requiere_accion_gerencial=excluded.requiere_accion_gerencial, confidencialidad=excluded.confidencialidad, activo=excluded.activo, updated_at=excluded.updated_at;
