-- Cargar las Direcciones del organigrama GADMR en el catálogo de áreas.
-- Idempotente. El "agregar cualquier otro" se hace desde Catálogos (jefaturas, EERSA, RIOBAMBA-EP, etc.).
insert into public.areas(nombre, activo) values
  ('DIRECCIÓN GENERAL DE GESTIÓN DE PLANIFICACIÓN, HÁBITAT Y DESARROLLO URBANÍSTICO', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN ESTRATÉGICA', true),
  ('PROCURADURÍA', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE LA COMUNICACIÓN', true),
  ('DIRECCIÓN DE AUDITORÍA INTERNA (CGE)', true),
  ('SECRETARÍA GENERAL', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN', true),
  ('DIRECCIÓN GENERAL DE TALENTO HUMANO', true),
  ('DIRECCIÓN GENERAL ADMINISTRATIVA', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN FINANCIERA', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE DESARROLLO ECONÓMICO Y TURISMO', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE CULTURA, DEPORTES, ARTE Y CONOCIMIENTO', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE JUSTICIA Y CONTROL MUNICIPAL', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE DESARROLLO SOCIAL E INCLUSIÓN', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE OBRAS PÚBLICAS', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN AMBIENTAL', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE MOVILIDAD', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE AVALÚOS, CATASTROS Y SIG', true),
  ('DIRECCIÓN GENERAL DE GESTIÓN DE PATRIMONIO', true)
on conflict (nombre) do update set activo = true;
